apiVersion: kbld.k14s.io/v1alpha1
kind: Config
sources:
  - image: app1
    path: ./src-app1 # <-- where to find app1 source
  - image: app2
    path: ./src-app2 # <-- where to find app2 source
    pack:
      build:
        builder: paketobuildpacks/builder:tiny
destinations:
  - image: app1
    newImage: docker.io/ciberkleid736/kbld-app1 # <-- where to push app1 image
    tags: [dockerfile]
  - image: app2
    newImage: docker.io/ciberkleid736/kbld-app2 # <-- where to push app2 image
    tags: [cnb]